# етап збірки
FROM node:18-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# етап виконання
FROM node:18-alpine
WORKDIR /app
# встановлюємо serve для роздачі статики
RUN npm install -g serve
# копіюємо зібрану директорію
COPY --from=builder /app/build ./build

EXPOSE 3001
# запускаємо сервер статики на порту 3001
CMD ["serve", "-s", "build", "-l", "3001"]
