version: '3.8'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: Forum
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "3000:3000"

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile.frontend
    depends_on:
      - backend
    ports:
      - "3001:3001"

volumes:
  db-data: